#server:
#  port: 80
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id : live-api
#          uri : lb://live-api
#          predicates:
#            - Path=/live-api/**
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedHeaders: "*"
#            allowedMethods: "*"
#      default-filters:
#        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
#    nacos:
#      discovery:
#        server-addr: host.docker.internal:8848
#        group: DEFAULT_GROUP
#        namespace: 05e9183f-7ab2-45fb-8a8e-ed4e4caf2e63
#  application:
#    name: gateway