spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8808/qiyu_live_common?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
  application:
    name: id-generate-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 83